cliente/urls.py
from django.urls import path

from .views import ClienteCreateView, ClienteDeleteView, ClienteListView, ClienteUpdateView, ContasReceberDeleteView,\
    ContasReceberListView, ContasReceberUpdateView, FiadoCreateView, buscar_conta_receber, buscar_revendedor, \
    lista_fiado, ContasReceberCreateView, codigo_acesso, FiadoUpdateView, \
    FiadoDeleteView, buscar_fiado


app_name = 'cliente'


urlpatterns = [
    path('novo_cliente/', ClienteCreateView.as_view(), name='cliente_create'),
    path('novo_fiado/', FiadoCreateView.as_view(), name='fiado_create'),
    path('lista_fiado/', lista_fiado.as_view(), name='lista_fiado'),
    path('conta_receber/', ContasReceberCreateView.as_view(), name='conta_receber'),
    path('codigo-acesso/', codigo_acesso, name='codigo_acesso'),
    path('lista_contasreceber/', ContasReceberListView.as_view(),
         name='lista_contasreceber'),
    path('conta_receber_edit/<int:pk>/',
         ContasReceberUpdateView.as_view(), name='conta_receber_edit'),
    path('conta_receber_delete/<int:pk>/',
         ContasReceberDeleteView.as_view(), name='conta_receber_delete'),
    path('fiado_edit/<int:pk>/',
         FiadoUpdateView.as_view(), name='fiado_edit'),
    path('fiado_delete/<int:pk>/',
         FiadoDeleteView.as_view(), name='fiado_delete'),
    path('lista_clientes/', ClienteListView.as_view(),
         name='lista_clientes'),
    path('cliente_edit/<int:pk>/',
         ClienteUpdateView.as_view(), name='cliente_edit'),
    path('cliente_delete/<int:pk>/',
         ClienteDeleteView.as_view(), name='cliente_delete'),
    path('buscar_fiado', buscar_fiado,
         name='buscar_fiado'),
    path('buscar_conta_receber/', buscar_conta_receber,
         name='buscar_conta_receber'),
    path('buscar_revendedor/', buscar_revendedor,
         name='buscar_revendedor'),

]

loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('cliente/', include('cliente.urls')),
    path('vendas/', include('vendas.urls')),
    path('gestao/', include('gestao.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliente/models.py
from django.utils import timezone
import re
from django.utils.text import slugify

from django.contrib.auth.models import User
from django.utils.html import format_html

from django.db import models
from django.forms import ValidationError
from utils.validacpf import valida_cpf


class Cliente(models.Model):
    codigo = models.CharField(
        max_length=4, verbose_name='Código', blank=True, null=True)
    usuario = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name='Usuário', blank=True, null=True)

    def __str__(self):
        return f'{self.usuario}'

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'


class Fiado(models.Model):
    data = models.DateField(default=timezone.now,
                            verbose_name='Data da compra')
    data_p = models.DateField(default=timezone.now,
                              verbose_name='Data do pagamento')
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT,
                                default=None, blank=True, null=True, verbose_name="Cliente")
    valor = models.FloatField(verbose_name="Valor da dívida")
    pagamento = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('C', 'Cartão'),
            ('D', 'Dinheiro'),
        )
    )
    status = models.CharField(
        default="D",
        max_length=1,
        choices=(
            ('D', 'Devendo'),
            ('P', 'Pago'),
        )
    )


class ContasReceber(models.Model):
    data = models.DateField(verbose_name="Data do pagamento")
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT,
                                default=None, blank=True, null=True, verbose_name="Cliente")
    valor = models.FloatField(verbose_name="Valor da dívida")
    pagamento = models.CharField(
        max_length=100, verbose_name="Tipo de pagamento")
    status = models.CharField(
        default="D",
        max_length=1,
        choices=(
            ('D', 'Devendo'),
            ('P', 'Pago'),
        )
    )

    class Meta:
        verbose_name = 'Contas a receber'
        verbose_name_plural = 'Contas a receber'

cliente/forms.py
from datetime import timedelta, timezone
from django import forms
from bootstrap_datepicker_plus.widgets import DateTimePickerInput

from . import models


class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = '__all__'


class FiadoForm(forms.ModelForm):
    class Meta:
        model = models.Fiado
        fields = ['data', 'cliente', 'valor', 'pagamento', 'status', 'data_p']
        widgets = {
            'data': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                }
            ),
            'data_p': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                }
            ),
        }


class ContasReceberForm(forms.ModelForm):
    class Meta:
        model = models.ContasReceber
        fields = '__all__'
        widgets = {
            'data': forms.DateInput(
                format='%Y-%m-%d',
                attrs={
                    'class': 'form-control',
                    'type': 'date',
                }
            ),
        }

cliente/views.py
from datetime import datetime
from utils.utils import cart_totals

from .forms import FiadoForm
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Cliente, Fiado, ContasReceber
from .forms import ClienteForm, FiadoForm, ContasReceberForm
from produto.models import Categoria, Produto, Tipo
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import threading

from django.db.models import Q


@login_required
def codigo_acesso(request):
    perfil = Cliente.objects.filter(usuario=request.user).first()

    # Verificar se o cliente já digitou o código de acesso nesta sessão
    codigo_acesso_digitado = request.session.get(
        'codigo_acesso_digitado', False)

    if not codigo_acesso_digitado:
        if not perfil or not perfil.codigo:
            return render(request, 'codigo_acesso.html', {'erro': 'Você não tem acesso ao catálogo de atacado, fale com a loja!'})
        else:
            # Se o perfil do cliente possui o código, mas ainda não foi digitado nesta sessão, solicite o código.
            if request.method == 'POST':
                codigo_digitado = request.POST.get('codigo', '')

                if codigo_digitado == perfil.codigo:
                    # Se o código estiver correto, armazene o indicador na sessão
                    request.session['codigo_acesso_digitado'] = True

                    nomes_produtos = Produto.objects.values_list(
                        'nome', flat=True).distinct()
                    produtos = Produto.objects.filter(
                        nome__in=nomes_produtos, is_primary=True).order_by('-destaque', '-id')
                    categorias = Categoria.objects.all()
                    tipos = Tipo.objects.all()

                    context = {
                        'produtos': produtos,
                        'categorias': categorias,
                        'tipos': tipos
                    }

                    # Acessar o carrinho da sessão e adicionar ao contexto
                    carrinho = request.session.get('carrinho', {})
                    totals = cart_totals(carrinho)
                    context['carrinho'] = carrinho
                    context['cart_totals'] = totals

                    return render(request, 'produto/lista_atacado.html', context)
                else:
                    return render(request, 'codigo_acesso.html', {'erro': 'Código inválido.'})
            else:
                return render(request, 'codigo_acesso.html')

    # Se o código já foi digitado nesta sessão e é válido, redirecione para a lista_atacado
    nomes_produtos = Produto.objects.values_list(
        'nome', flat=True).distinct()
    produtos = Produto.objects.filter(
        nome__in=nomes_produtos, is_primary=True).order_by('-destaque', '-id')
    categorias = Categoria.objects.all()
    tipos = Tipo.objects.all()

    context = {
        'produtos': produtos,
        'categorias': categorias,
        'tipos': tipos
    }

    # Acessar o carrinho da sessão e adicionar ao contexto
    carrinho = request.session.get('carrinho', {})
    totals = cart_totals(carrinho)
    context['carrinho'] = carrinho
    context['cart_totals'] = totals

    return render(request, 'produto/lista_atacado.html', context)


class ClienteCreateView(LoginRequiredMixin, CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'cliente_create.html'
    success_url = reverse_lazy('cliente:lista_clientes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Novo Revendedor'
        return context


class ClienteListView(LoginRequiredMixin, ListView):
    model = Cliente
    context_object_name = 'clientes'
    template_name = 'cliente/lista_clientes.html'
    paginate_by = 10
    ordering = ['-id']


class ClienteUpdateView(LoginRequiredMixin, UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'cliente_create.html'
    success_url = reverse_lazy('cliente:lista_clientes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Revendedor'
        return context


class ClienteDeleteView(LoginRequiredMixin, DeleteView):
    model = Cliente
    template_name = 'cliente_delete.html'
    success_url = reverse_lazy('cliente:lista_clientes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Excluir Revendedor'
        return context


class ContasReceberCreateView(LoginRequiredMixin, CreateView):
    model = ContasReceber
    form_class = ContasReceberForm
    template_name = 'contasreceber_create.html'
    success_url = reverse_lazy('cliente:lista_contasreceber')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Conta a Receber'
        return context


class ContasReceberListView(LoginRequiredMixin, ListView):
    model = ContasReceber
    context_object_name = 'contasreceber'
    template_name = 'cliente/lista_contasreceber.html'
    paginate_by = 10
    ordering = ['-id']


class ContasReceberUpdateView(LoginRequiredMixin, UpdateView):
    model = ContasReceber
    form_class = ContasReceberForm
    template_name = 'contasreceber_create.html'
    success_url = reverse_lazy('cliente:lista_contasreceber')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Conta a Receber'
        return context


class ContasReceberDeleteView(LoginRequiredMixin, DeleteView):
    model = ContasReceber
    template_name = 'contasreceber_delete.html'
    success_url = reverse_lazy('cliente:lista_contasreceber')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Excluir Conta a Receber'
        return context


class FiadoCreateView(LoginRequiredMixin, CreateView):
    model = Fiado
    form_class = FiadoForm
    template_name = 'fiado_create.html'
    success_url = reverse_lazy('cliente:lista_fiado')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Adicionar Fiado'
        return context

    def form_valid(self, form):
        fiado = form.save(commit=False)
        fiado.save()
        return super().form_valid(form)


class lista_fiado(LoginRequiredMixin, ListView):
    model = Fiado
    context_object_name = 'fiados'
    template_name = 'cliente/lista_fiado.html'
    paginate_by = 10
    ordering = ['-id']


class FiadoUpdateView(LoginRequiredMixin, UpdateView):
    model = Fiado
    form_class = FiadoForm
    template_name = 'fiado_create.html'
    success_url = reverse_lazy('cliente:lista_fiado')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Fiado'
        return context


class FiadoDeleteView(LoginRequiredMixin, DeleteView):
    model = Fiado
    template_name = 'fiado_delete.html'
    success_url = reverse_lazy('cliente:lista_fiado')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Excluir Fiado?'
        return context


def buscar_fiado(request):
    query = request.GET.get('q')
    resultados = None

    if query:
        resultados = Fiado.objects.filter(Q(cliente__nome__icontains=query))

    return render(request, 'cliente/lista_fiado.html', {'fiados': resultados})


def buscar_conta_receber(request):
    query = request.GET.get('q')
    resultados = None

    if query:
        resultados = ContasReceber.objects.filter(
            Q(cliente__nome__icontains=query))

    return render(request, 'cliente/lista_contasreceber.html', {'contasreceber': resultados})


def buscar_revendedor(request):
    query = request.GET.get('q')
    resultados = None

    if query:
        resultados = Cliente.objects.filter(
            Q(usuario__username__icontains=query))

    return render(request, 'cliente/lista_clientes.html', {'clientes': resultados})

cliente/templates/cliente/lista_clientes.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

 <div class="flex items-center justify-between mb-4">
  <div class="flex-shrink-0"><br><br><br>
   <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Revendedores</span><br><br>
  </div>
 </div>
 <div class="row">
  <div class="col-lg-4 col-sm-4">
   <div class="d-flex justify-content-center">
    <form class="input-group" action="{% url 'cliente:buscar_revendedor' %}" method="GET">
     <input type="text" class="form-control" placeholder="Pesquisar pelo Nome" name="q" aria-label="Pesquisar">
     <div class="input-group-append">
      <button class="btn btn-outline-primary" type="submit">
       <i class="fas fa-search"></i>
      </button>
     </div>
    </form>
   </div>
  </div>
 </div><br>

 <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
   <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
    <tr>
     <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
      Nome
     </th>
     <th scope="col" class="px-6 py-3">
      Código
     </th>

     <th scope="col"
      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
      Ações
     </th>
    </tr>
   </thead>
   <tbody>
    {% for cliente in clientes %}
    <tr class="border-b border-gray-200 dark:border-gray-700">
     <th scope="row"
      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
      {{ cliente.usuario }}
     </th>
     <td class="px-6 py-4">
      {{ cliente.codigo }}
     </td>

     <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
      <a href="{% url 'cliente:cliente_edit' cliente.id %}">
       <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
      </a>
      <a href="{% url 'cliente:cliente_delete' cliente.id %}">
       <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
      </a>
     </td>
    </tr>
    {% endfor %}
   </tbody>
  </table>
 </div>
</div>


{% include 'parciais/_pagination.html' %}

{% endblock %}

cliente/templates/cliente/lista_contasreceber.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

 <div class="flex items-center justify-between mb-4">
  <div class="flex-shrink-0"><br><br><br>
   <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Contas a receber!</span><br><br>
  </div>
 </div>
 <div class="row">
  <div class="col-lg-4 col-sm-4">
   <div class="d-flex justify-content-center">
    <form class="input-group" action="{% url 'cliente:buscar_conta_receber' %}" method="GET">
     <input type="text" class="form-control" placeholder="Pesquisar pelo Nome" name="q" aria-label="Pesquisar">
     <div class="input-group-append">
      <button class="btn btn-outline-primary" type="submit">
       <i class="fas fa-search"></i>
      </button>
     </div>
    </form>
   </div>
  </div>
 </div><br>

 <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
   <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
    <tr>
     <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
      Data
     </th>
     <th scope="col" class="px-6 py-3">
      Cliente
     </th>
     <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
      Valor a receber
     </th>
     <th scope="col" class="px-6 py-3">
      Tipo de pagamento
     </th>
     <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
      Status
     </th>
     <th scope="col" class="px-6 py-4">
      Ações
     </th>

    </tr>
   </thead>
   <tbody>
    {% for conta in contasreceber %}
    <tr class="border-b border-gray-200 dark:border-gray-700">
     <th scope="row"
      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
      {{ conta.data }}
     </th>
     <td class="px-6 py-4">
      {{ conta.cliente }}
     </td>
     <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
      {{ conta.valor|floatformat:2 }}
     </td>
     <td class="px-6 py-4">
      {{ conta.pagamento }}
     </td>
     <td
      class="px-6 py-4 bg-gray-50 dark:bg-gray-800 {% if conta.status == 'D' %}text-red-500{% elif conta.status == 'P' %}text-green-500{% endif %}">
      {{ conta.get_status_display }}
     </td>
     <td class="px-6 py-4">
      <a href="{% url 'cliente:conta_receber_edit' conta.id %}">
       <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
      </a>
      <a href="{% url 'cliente:conta_receber_delete' conta.id %}">
       <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
      </a>
     </td>
    </tr>
    {% endfor %}
   </tbody>
  </table>
 </div>
</div>


{% include 'parciais/_pagination.html' %}

{% endblock %}

cliente/templates/cliente/lista_fiado.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

  <div class="flex items-center justify-between mb-4">
    <div class="flex-shrink-0"><br><br><br>
      <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Fiados</span><br><br>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-sm-4">
      <div class="d-flex justify-content-center">
        <form class="input-group" action="{% url 'cliente:buscar_fiado' %}" method="GET">
          <input type="text" class="form-control" placeholder="Pesquise pelo nome do Cliente" name="q"
            aria-label="Pesquisar">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div><br>

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Data da compra
          </th>
          <th scope="col" class="px-6 py-3">
            Data do pagamento
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Valor
          </th>
          <th scope="col" class="px-6 py-3">
            Cliente
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Tipo de pagamento
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Ações
          </th>
        </tr>
      </thead>
      <tbody>
        {% for fiado in fiados %}
        <tr class="border-b border-gray-200 dark:border-gray-700">
          <th scope="row"
            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
            {{ fiado.data }}
          </th>
          <td class="px-6 py-4">
            {{ fiado.data_p }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            {{ fiado.valor|floatformat:2 }}
          </td>
          <td class="px-6 py-4">
            {{ fiado.cliente }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            {{ fiado.get_pagamento_display }}
          </td>
          <td
            class="px-6 py-4 {% if fiado.status == 'D' %}text-red-500{% elif fiado.status == 'P' %}text-green-500{% endif %}">
            {{ fiado.get_status_display }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            <a href="{% url 'cliente:fiado_edit' fiado.id %}">
              <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
            </a>
            <a href="{% url 'cliente:fiado_delete' fiado.id %}">
              <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
            </a>

          </td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>



{% include 'parciais/_pagination.html' %}

{% endblock %}