gestao/urls.py
from django.urls import path

from . import views

app_name = 'gestao'

urlpatterns = [
    path('relatorio/', views.RelatorioView.as_view(), name='relatorio'),
    path('dashboard/', views.Dashboard.as_view(),
         name='dashboard'),
    path('produtos_mais_vendidos/', views.TopProdutosView,
         name='produtos_mais_vendidos'),
    path('venas_gerais/', views.VendasGeraisView,
         name='vendas_gerais'),
    path('relatorio_financeiro/', views.RelatorioFinanceiroView,
         name='relatorio_financeiro'),
    path('vendedores_que_mais_vendem/', views.TopVendedorView,
         name='vendedores_mais_vendem'),
    path('clientes_mais_compram/', views.TopPerfisView,
         name='clientes_mais_compram'),
    path('caixa/', views.Caixa.as_view(),
         name='caixa'),
    path('lista_caixa/', views.CaixaAbertoListView.as_view(),
         name='lista_caixa'),
    path('caixas/<int:pk>/', views.CaixaAbertoDetail.as_view(),
         name='caixa_aberto_detail'),
    path('caixa_aberto/<int:pk>/reforco/',
         views.reforco_caixa, name='reforco_caixa'),
    path('caixa_aberto/<int:pk>/retirada/',
         views.retirada_caixa, name='retirada_caixa'),
    path('caixa_edit/<int:pk>/',
         views.CaixaUpdateView.as_view(), name='caixa_edit'),
    path('caixa_delete/<int:pk>/',
         views.CaixaDeleteView.as_view(), name='caixa_delete'),
    path('buscar_caixa_aberto', views.buscar_caixa_aberto,
         name='buscar_caixa_aberto'),
    path('perfil_detalhe/<int:perfil_id>/',
         views.PerfilDetalheView, name='perfil_detalhe'),
    path('perfil_detalhe/<int:perfil_id>/<str:tipo_venda>/',
         views.PerfilDetalheView, name='perfil_detalhe_tipo_venda'),
    path('relatorio_caixa_por_data/', views.RelatorioCaixaPorDataView.as_view(),
         name='relatorio_caixa_por_data'),





]

loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('cliente/', include('cliente.urls')),
    path('vendas/', include('vendas.urls')),
    path('gestao/', include('gestao.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestao/models.py
from django.db import models
from django.utils import timezone
from pedido.models import Devolucao


class CaixaAberto(models.Model):
    nome = models.CharField(max_length=65, verbose_name='Apelido do Caixa')
    valor = models.FloatField(verbose_name='Valor de Abertura')
    status = models.CharField(
        default="A",
        max_length=1,
        choices=(
            ('A', 'Aberto'),
            ('F', 'Fechado'),
        )
    )
    data = models.DateField(default=timezone.now,
                            verbose_name='Data de Abertura')

    def __str__(self):
        return self.nome


class Reforço(models.Model):
    reforço = models.FloatField(verbose_name='Valor do Reforço')
    data = models.DateField(default=timezone.now,
                            verbose_name='Data do reforço')


class Retirada(models.Model):
    retirada = models.FloatField(verbose_name='Valor da Retirada')
    observacao = models.CharField(
        max_length=100, verbose_name='Observação', blank=True, null=True)
    data = models.DateField(default=timezone.now,
                            verbose_name='Data da retirada')

gestao/forms.py
from django import forms
from . import models


class CaixaAbertoForm(forms.ModelForm):
    class Meta:
        model = models.CaixaAberto
        fields = ['nome', 'valor']


class ReforçoForm(forms.ModelForm):
    class Meta:
        model = models.Reforço
        fields = ['reforço']


class RetiradaForm(forms.ModelForm):
    class Meta:
        model = models.Retirada
        fields = ['retirada', 'observacao']

gestao/views.py
from django.views import View
from perfil.models import Perfil
from perfil.models import Perfil
from .models import CaixaAberto
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, CreateView
from . models import CaixaAberto, Retirada, Reforço
from . forms import CaixaAbertoForm, ReforçoForm, RetiradaForm
from pedido.models import Devolucao, Pedido, ItemPedido
from cliente.models import Fiado
from produto.models import Produto
from django.views.generic import DetailView, ListView, TemplateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from produto.models import Produto
from datetime import date, datetime
from django.db.models import Sum, Avg, Count, F, Sum, Case, When, IntegerField, Subquery, OuterRef, Value, DecimalField
from django.db.models import Q
from django.db.models.functions import Coalesce
from collections import Counter

from vendas.models import Vendedor


class RelatorioView(LoginRequiredMixin, TemplateView):
    template_name = 'relatorio.html'


@login_required
def RelatorioFinanceiroView(request):
    data_inicio = request.GET.get('data_inicio')
    data_fim = request.GET.get('data_fim')

    # Converter as datas para o formato correto (dd/mm/yyyy)
    data_inicio = datetime.strptime(
        data_inicio, '%d/%m/%Y').date() if data_inicio else None
    data_fim = datetime.strptime(
        data_fim, '%d/%m/%Y').date() if data_fim else None

    itens_aprovados = ItemPedido.objects.filter(pedido__status='A')
    pedidos_aprovados = Pedido.objects.filter(status='A')
    devolucoes = Devolucao.objects.all()

    # Aplicar filtro de datas, se fornecidas
    if data_inicio and data_fim:
        itens_aprovados = itens_aprovados.filter(
            pedido__data__range=(data_inicio, data_fim))
        pedidos_aprovados = pedidos_aprovados.filter(
            data__range=(data_inicio, data_fim))

    produtos_quantidades = (
        itens_aprovados
        .values('produto', 'produto_id', 'produto_modalidade', 'produto_cor')
        .annotate(quantidade=Sum('quantidade'))
        .order_by('-quantidade')
    )

    perfis_pedidos_aprovados = Perfil.objects.annotate(
        num_pedidos_aprovados=Count('usuario__pedido', filter=Q(
            usuario__pedido__status='A', usuario__pedido__data__range=(data_inicio, data_fim))),
        total_pedidos_aprovados=Sum(
            Case(
                When(usuario__pedido__status='A', usuario__pedido__data__range=(
                    data_inicio, data_fim), then='usuario__pedido__total'),
                default=0,
                output_field=IntegerField()
            )
        ),
        modalidade_pedido=F('usuario__pedido__itempedido__produto_modalidade')
    ).order_by('-num_pedidos_aprovados')

    vendedores_pedidos_aprovados = Vendedor.objects.annotate(num_pedidos_aprovados=Count('pedido', filter=Q(
        pedido__status='A', pedido__data__range=(data_inicio, data_fim)))).order_by('-num_pedidos_aprovados')[:10]

    quantidade_aprovados = pedidos_aprovados.count()
    quantidade_itens_aprovados = pedidos_aprovados.aggregate(
        total_itens=Sum('qtd_total'))['total_itens'] or 0
    total_pedidos = pedidos_aprovados.aggregate(total_pedidos=Sum('total'))[
        'total_pedidos'] or 0
    quantidade_devolucoes = devolucoes.count()
    soma_devolucoes = devolucoes.aggregate(total_devolucoes=Sum('pedido__total'))[
        'total_devolucoes'] or 0

    context = {
        'produtos_quantidades': produtos_quantidades,
        'perfis_pedidos_aprovados': perfis_pedidos_aprovados,
        'vendedores_pedidos_aprovados': vendedores_pedidos_aprovados,
        'quantidade_aprovados': quantidade_aprovados,
        'quantidade_itens_aprovados': quantidade_itens_aprovados,
        'total_pedidos': total_pedidos,
        'data_inicio': data_inicio,
        'data_fim': data_fim,
        'quantidade_devolucoes': quantidade_devolucoes,
        'soma_devolucoes': soma_devolucoes,
    }

    return render(request, 'gestao/relatorio_financeiro.html', context)


@login_required
def TopProdutosView(request):
    data_inicio = request.GET.get('data_inicio')
    data_fim = request.GET.get('data_fim')

    # Converter as datas para o formato correto (dd/mm/yyyy)
    data_inicio = datetime.strptime(
        data_inicio, '%d/%m/%Y').date() if data_inicio else None
    data_fim = datetime.strptime(
        data_fim, '%d/%m/%Y').date() if data_fim else None

    subquery = ItemPedido.objects.filter(
        produto=OuterRef('produto'),
        produto_cor=OuterRef('produto_cor'),
        pedido__status='A'
    ).annotate(
        preco_item=Case(
            When(preco_promocional__gt=0, then=F('preco_promocional')),
            default=F('preco'),
            output_field=DecimalField()
        )
    ).values('produto', 'produto_cor').annotate(
        total=Sum('preco_item')
    ).values('total')

    itens_aprovados = ItemPedido.objects.filter(pedido__status='A')

    # Aplicar filtro de datas, se fornecidas
    if data_inicio and data_fim:
        itens_aprovados = itens_aprovados.filter(
            pedido__data__range=(data_inicio, data_fim))

    produtos_quantidades = (
        itens_aprovados
        .values('produto', 'produto_cor', 'produto_modalidade')
        .annotate(quantidade=Sum('quantidade'))
        .annotate(pedido_total=Subquery(subquery))
        .order_by('-quantidade')[:10]
    )

    context = {
        'produtos_quantidades': produtos_quantidades,
        'data_inicio': data_inicio,
        'data_fim': data_fim,
    }

    return render(request, 'gestao/produtos_mais_vendidos.html', context)


@login_required
def TopPerfisView(request):
    data_inicio = request.GET.get('data_inicio')
    data_fim = request.GET.get('data_fim')

    # Converter as datas para o formato correto (dd/mm/yyyy)
    data_inicio = datetime.strptime(
        data_inicio, '%d/%m/%Y').date() if data_inicio else None
    data_fim = datetime.strptime(
        data_fim, '%d/%m/%Y').date() if data_fim else None

    pedidos_aprovados = Pedido.objects.filter(status='A')
    # Aplicar filtro de datas, se fornecidas
    if data_inicio and data_fim:
        pedidos_aprovados = pedidos_aprovados.filter(
            data__range=(data_inicio, data_fim))

    perfis_pedidos_aprovados = Perfil.objects.annotate(
        num_pedidos_aprovados=Count('usuario__pedido', filter=Q(
            usuario__pedido__status='A', usuario__pedido__data__range=(data_inicio, data_fim))),
        total_pedidos_aprovados=Sum(
            Case(
                When(usuario__pedido__status='A', usuario__pedido__data__range=(
                    data_inicio, data_fim), then='usuario__pedido__total'),
                default=0,
                output_field=IntegerField()
            )
        ),
        modalidade_pedido=F('usuario__pedido__itempedido__produto_modalidade')
    ).order_by('-num_pedidos_aprovados')

    context = {
        'perfis_pedidos_aprovados': perfis_pedidos_aprovados,
        'data_inicio': data_inicio,
        'data_fim': data_fim
    }

    return render(request, 'gestao/clientes_que_mais_compram.html', context)


@login_required
def PerfilDetalheView(request, perfil_id, tipo_venda=None):
    perfil = get_object_or_404(Perfil, pk=perfil_id)
    data_inicio = request.GET.get('data_inicio')
    data_fim = request.GET.get('data_fim')

    # Converter as datas para o formato correto (dd/mm/yyyy)
    data_inicio = datetime.strptime(
        data_inicio, '%d/%m/%Y').date() if data_inicio else None
    data_fim = datetime.strptime(
        data_fim, '%d/%m/%Y').date() if data_fim else None

    context = {
        'perfil': perfil,
        'tipo_venda': tipo_venda,
        'total_varejo': 0,
        'total_atacado': 0,
        'quantidade_varejo': 0,
        'quantidade_atacado': 0,
        'data_inicio': data_inicio,
        'data_fim': data_fim,
    }

    if tipo_venda == 'V':  # Vendas no Varejo
        itens_pedido = ItemPedido.objects.filter(
            pedido__usuario=perfil.usuario, pedido__status='A', produto_modalidade='V')

        pedidos_aprovados = Pedido.objects.filter(status='A')

        if data_inicio and data_fim:
            pedidos_aprovados = pedidos_aprovados.filter(
                data__range=(data_inicio, data_fim))

        itens_pedido = itens_pedido.filter(pedido__in=pedidos_aprovados)

        total_varejo = sum(
            item_pedido.preco_promocional or item_pedido.preco for item_pedido in itens_pedido)
        quantidade_varejo = sum(
            item_pedido.quantidade for item_pedido in itens_pedido)

        context['itens_pedido'] = itens_pedido
        context['total_varejo'] = total_varejo
        context['quantidade_varejo'] = quantidade_varejo

    elif tipo_venda == 'A':  # Vendas no Atacado
        itens_pedido = ItemPedido.objects.filter(
            pedido__usuario=perfil.usuario, pedido__status='A', produto_modalidade='A')

        pedidos_aprovados = Pedido.objects.filter(status='A')

        if data_inicio and data_fim:
            pedidos_aprovados = pedidos_aprovados.filter(
                data__range=(data_inicio, data_fim))

        itens_pedido = itens_pedido.filter(pedido__in=pedidos_aprovados)

        total_atacado = sum(
            item_pedido.preco_promocional or item_pedido.preco for item_pedido in itens_pedido)
        quantidade_atacado = sum(
            item_pedido.quantidade for item_pedido in itens_pedido)

        context['itens_pedido'] = itens_pedido
        context['total_atacado'] = total_atacado
        context['quantidade_atacado'] = quantidade_atacado

    return render(request, 'gestao/perfil_detalhe.html', context)


@login_required
def TopVendedorView(request):
    data_inicio = request.GET.get('data_inicio')

gestao/templates/gestao/caixa_create.html
{% extends 'parciais/base_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load omfilters %}

{% block content %}


<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

 <div class="flex items-center justify-between mb-4">
  <div class="flex-shrink-0"><br><br><br>
   <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">{{ title }}</span><br><br>
  </div>
 </div>

 <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <form method="post">
   {% csrf_token %}
   {{ form|crispy }}

   <div class="form-group">
    <div class="col-md-12 text-right">
     <button type="submit" class="btn btn-success">Salvar</button>
     <a href="{% url 'gestao:lista_caixa' %}" class="btn btn-secondary">Cancelar</a>

    </div>
   </div>
  </form>
 </div>
</div>


{% endblock %}

gestao/templates/gestao/clientes_que_mais_compram.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}
<main>


  <div class="pt-6 px-4">
    <div class="grid grid-cols-1 2xl:grid-cols-2 xl:gap-4 my-4">
      <!-- Sessions by device Card -->
      <div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8 ">

        <!-- Card Title -->
        <h3 class="text-xl leading-none font-bold text-gray-900 mb-10">Clientes que mais compram</h3>




        <!-- Tabela de produtos mais vendidos -->
        <div class="block w-full overflow-x-auto">
          <table class="items-center w-full bg-transparent border-collapse">
            <!-- Cabeçalho da tabela -->
            <thead>
              <tr>
                <th
                  class="px-4 bg-gray-50 text-gray-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                  Perfil</th>
                <th
                  class="px-4 bg-gray-50 text-gray-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap min-w-140-px">
                  Modalidade</th>
                <th
                  class="px-4 bg-gray-50 text-gray-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap min-w-140-px">
                  Detalhe</th>


              </tr>
            </thead>
            <!-- Linhas da tabela -->
            <tbody class="divide-y divide-gray-100">
              {% for perfil in perfis_pedidos_aprovados %}
              <tr class="text-gray-500">
                <th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-left">
                  {{ perfil }}</th>
                {% if perfil.modalidade_pedido %}
                <td class="border-t-0 px-4 align-middle text-xs font-medium text-gray-900 whitespace-nowrap p-4">
                  {{ perfil.modalidade_pedido }}</td>
                {% else %}
                <td class="border-t-0 px-4 align-middle text-xs font-medium text-gray-900 whitespace-nowrap p-4">
                  0</td>
                {% endif %}
                <td class="border-t-0 px-4 align-middle text-xs font-medium text-gray-900 whitespace-nowrap p-4">

                  <a href="{% url 'gestao:perfil_detalhe' perfil.id %}">Detalhe</a>
                </td>
              </tr>

              {% endfor %}
            </tbody>
          </table>
        </div>

      </div>

    </div>
  </div>


</main>
{% endblock %}

gestao/templates/gestao/lista_caixa.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

  <div class="flex items-center justify-between mb-4">
    <div class="flex-shrink-0"><br><br><br>
      <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Lista de Caixas já abertos!</span><br><br>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-sm-4">
      <div class="d-flex justify-content-center">
        <form class="input-group" action="{% url 'gestao:buscar_caixa_aberto' %}" method="GET">
          <input type="text" class="form-control" placeholder="Pesquise pelo nome" name="q" aria-label="Pesquisar">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div><br>

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Nome
          </th>
          <th scope="col" class="px-6 py-3">
            Valor de abertura
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Data
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Detalhe
          </th>
          <th scope="col" class="px-6 py-3">
            Ações
          </th>
        </tr>
      </thead>
      <tbody>
        {% for caixa in caixas %}
        <tr class="border-b border-gray-200 dark:border-gray-700">
          <th scope="row"
            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">

            {{ caixa.nome }}
          </th>
          <td class="px-6 py-4">
            {{ caixa.valor|floatformat:2 }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            {{ caixa.data }}
          </td>
          <td
            class="px-6 py-4 {% if caixa.status == 'A' %}text-green-500{% elif caixa.status == 'F' %}text-red-500{% endif %}">
            {{ caixa.get_status_display }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            <a href="{% url 'gestao:caixa_aberto_detail' caixa.id %}"><i class="fa-solid fa-magnifying-glass-plus fa-xl"
                style="color: #028a00;"></i></a>
          </td>
          <td class="px-6 py-4">
            <a href="{% url 'gestao:caixa_edit' caixa.id %}">
              <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
            </a>
            <a href="{% url 'gestao:caixa_delete' caixa.id %}">
              <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


{% include 'parciais/_pagination.html' %}

{% endblock %}

gestao/templates/gestao/lista_contaspagar.html
{% extends "includes/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

 <div class="flex items-center justify-between mb-4">
  <div class="flex-shrink-0"><br><br><br>
   <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Contas a pagar!</span><br><br>
  </div>

 </div>

 <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
   <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
    <tr>
     <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
      Data
     </th>
     <th scope="col" class="px-6 py-3">
      Fornecedor
     </th>
     <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
      Valor a pagar
     </th>
     <th scope="col" class="px-6 py-3">
      Tipo de pagamento
     </th>

    </tr>
   </thead>
   <tbody>
    {% for conta in contaspagar %}
    <tr class="border-b border-gray-200 dark:border-gray-700">
     <th scope="row"
      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
      {{ conta.data }}
     </th>
     <td class="px-6 py-4">
      {{ conta.fornecedor }}
     </td>
     <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
      {{ conta.valor }}
     </td>
     <td class="px-6 py-4">
      {{ conta.pagamento }}
     </td>
    </tr>
    {% endfor %}
   </tbody>
  </table>
 </div>
</div>


{% include 'parciais/_pagination.html' %}

{% endblock %}

gestao/templates/gestao/perfil_detalhe.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Detalhes{% endblock %}

{% block content %}
<main>


  <div class="pt-6 px-4">
    <div class="grid grid-cols-1 2xl:grid-cols-2 xl:gap-4 my-4">
      <!-- Sessions by device Card -->
      <div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8 "><br><br><br><br><br><br>

        <!-- Card Title -->
        <h4 class="text-lg leading-none font-bold text-gray-900 mt-8 mb-4">Filtrar por data:</h4>
        <form method="get">
          <div class="flex mb-4 grid justify-content-start align-items-center">
            <label for="data_inicio" class="mr-2">Início:</label>
            <input type="text" name="data_inicio" id="data_inicio" class="px-2 py-1 border rounded datepicker"
              autocomplete="off" value="{{ request.GET.data_inicio }}">
            <label for="data_fim" class="ml-4 mr-2">Fim:</label>
            <input type="text" name="data_fim" id="data_fim" class="px-2 py-1 border rounded datepicker"
              autocomplete="off" value="{{ request.GET.data_fim }}">
            <button type="submit" class="mr-2 px-4 py-1 bg-blue-500 text-black rounded">Filtrar</button>
            <button type="submit" class="mr-2 px-4 py-1 bg-blue-500 text-black rounded">
            </button>
          </div>
        </form>
        <h3 class="text-xl leading-none font-bold text-gray-900 mb-10">Detalhes do Perfil</h3>

        <p>Nome: {{ perfil.usuario }}</p>
        <!-- Adicione aqui outros detalhes do perfil -->

        <h4 class="text-lg leading-none font-bold text-gray-900 mt-8 mb-4">Selecione o tipo de venda:</h4>
        <p>
          <a href="{% url 'gestao:perfil_detalhe_tipo_venda' perfil.id 'V' %}">Vendas no Varejo</a> |
          <a href="{% url 'gestao:perfil_detalhe_tipo_venda' perfil.id 'A' %}">Vendas no Atacado</a>
        </p>

        {% if tipo_venda %}
        {% if tipo_venda == 'V' %}
        <h4 class="text-lg leading-none font-bold text-gray-900 mt-8 mb-4">Compras no Varejo</h4>
        {% elif tipo_venda == 'A' %}
        <h4 class="text-lg leading-none font-bold text-gray-900 mt-8 mb-4">Compras no Atacado</h4>
        {% endif %}
        {% if tipo_venda %}
        {% if tipo_venda == 'V' %}
        <p>Total Varejo: R$ {{ total_varejo }}</p>
        <p>Quantidade Varejo: {{ quantidade_varejo }}</p>

        {% elif tipo_venda == 'A' %}
        <p>Total Atacado: R$ {{ total_atacado }}</p>
        <p>Quantidade Atacado: {{ quantidade_atacado }}</p>

        {% endif %}
        {% endif %}
        {% if itens_pedido %}
        <table class="items-center w-full bg-transparent border-collapse">
          <thead>
            <tr>
              <th
                class="px-2 py-2 bg-gray-50 text-gray-700 align-middle text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                Produto
              </th>
              <th
                class="px-2 py-2 bg-gray-50 text-gray-700 align-middle text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                Quantidade
              </th>
              <th
                class="px-2 py-2 bg-gray-50 text-gray-700 align-middle text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                Preço
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100">
            {% for item_pedido in itens_pedido %}
            <tr class="text-gray-500">
              <th class="border-t-0 px-2 py-2 align-middle text-sm font-normal whitespace-nowrap">
                {{ item_pedido.produto }}-{{ item_pedido.produto_cor }}
              </th>
              <td class="border-t-0 px-2 py-2 align-middle text-xs font-medium text-gray-900 whitespace-nowrap">
                {{ item_pedido.quantidade }}
              </td>
              {% if item_pedido.preco_promocional %}
              <td class="border-t-0 px-2 py-2 align-middle text-xs font-medium text-gray-900 whitespace-nowrap">
                {{ item_pedido.preco_promocional|formata_preco }}
              </td>
              {% else %}
              <td class="border-t-0 px-2 py-2 align-middle text-xs font-medium text-gray-900 whitespace-nowrap">
                {{ item_pedido.preco|formata_preco }}
              </td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>Nenhum item do pedido encontrado para este tipo de venda.</p>
        {% endif %}
        {% endif %}



      </div>

    </div>

  </div>



</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.9.0/dist/js/bootstrap-datepicker.min.js"></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.9.0/dist/locales/bootstrap-datepicker.pt-BR.min.js"></script>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({
      format: 'dd/mm/yyyy',
      autoclose: true,
      todayHighlight: true,
      language: 'pt-BR'
    });
  });
</script>
{% endblock %}