gestao/urls.py
from django.urls import path

from . import views

app_name = 'gestao'

urlpatterns = [
    path('relatorio/', views.RelatorioView.as_view(), name='relatorio'),
    path('dashboard/', views.Dashboard.as_view(),
         name='dashboard'),
    path('produtos_mais_vendidos/', views.TopProdutosView,
         name='produtos_mais_vendidos'),
    path('venas_gerais/', views.VendasGeraisView,
         name='vendas_gerais'),
    path('relatorio_financeiro/', views.RelatorioFinanceiroView,
         name='relatorio_financeiro'),
    path('vendedores_que_mais_vendem/', views.TopVendedorView,
         name='vendedores_mais_vendem'),
    path('clientes_mais_compram/', views.TopPerfisView,
         name='clientes_mais_compram'),
    path('caixa/', views.Caixa.as_view(),
         name='caixa'),
    path('lista_caixa/', views.CaixaAbertoListView.as_view(),
         name='lista_caixa'),
    path('caixas/<int:pk>/', views.CaixaAbertoDetail.as_view(),
         name='caixa_aberto_detail'),
    path('caixa_aberto/<int:pk>/reforco/',
         views.reforco_caixa, name='reforco_caixa'),
    path('caixa_aberto/<int:pk>/retirada/',
         views.retirada_caixa, name='retirada_caixa'),
    path('caixa_edit/<int:pk>/',
         views.CaixaUpdateView.as_view(), name='caixa_edit'),
    path('caixa_delete/<int:pk>/',
         views.CaixaDeleteView.as_view(), name='caixa_delete'),
    path('buscar_caixa_aberto', views.buscar_caixa_aberto,
         name='buscar_caixa_aberto'),
    path('perfil_detalhe/<int:perfil_id>/',
         views.PerfilDetalheView, name='perfil_detalhe'),
    path('perfil_detalhe/<int:perfil_id>/<str:tipo_venda>/',
         views.PerfilDetalheView, name='perfil_detalhe_tipo_venda'),
    path('relatorio_caixa_por_data/', views.RelatorioCaixaPorDataView.as_view(),
         name='relatorio_caixa_por_data'),





]

loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('cliente/', include('cliente.urls')),
    path('vendas/', include('vendas.urls')),
    path('gestao/', include('gestao.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path

from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:id>', views.pagar, name='pagar'),
    path('pedido_sucesso/', views.SucessoView.as_view(), name='pedido_sucesso'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('salvarpedido_admin/', views.SalvarPedidoAdmin.as_view(),
         name='salvarpedido_admin'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
    path('lista_admin/', views.lista_admin.as_view(), name='lista_admin'),
    path('detalhe_admin/<int:pk>',
         views.detalhe_admin, name='detalhe_admin'),
    path('pedido/<int:pk>/excluir/', views.excluir_pedido, name='excluir_pedido'),
    path('nova_devolucao/', views.DevolucaoCreateView.as_view(),
         name='devolucao_create'),
    path('criar_novo_pedido/', views.criar_novo_pedido.as_view(),
         name='criar_novo_pedido'),
    path('lista_devolucao/', views.DevolucaoListView.as_view(),
         name='lista_devolucao'),
    path('devolucao_edit/<int:pk>/',
         views.DevolucaoUpdateView.as_view(), name='devolucao_edit'),
    path('devolucao_delete/<int:pk>/',
         views.DevolucaoDeleteView.as_view(), name='devolucao_delete'),
    path('pedido_edit/<int:pk>/',
         views.PedidoUpdateView.as_view(), name='pedido_edit'),
    path('buscar_pedido', views.buscar_pedido,
         name='buscar_pedido'),
    path('buscar_devolucao', views.buscar_devolucao,
         name='buscar_devolucao'),
    path('novo_cupom/', views.CupomCreateView.as_view(),
         name='cupom_create'),
    path('lista_cupom/', views.CupomListView.as_view(),
         name='lista_cupom'),
    path('cupom_edit/<int:pk>/',
         views.CupomUpdateView.as_view(), name='cupom_edit'),
    path('cupom_delete/<int:pk>/',
         views.CupomDeleteView.as_view(), name='cupom_delete'),






]

perfil/urls.py
from django.urls import path

from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('lista_perfis/', views.PerfilListView.as_view(),
         name='lista_perfis'),
    path('buscar_perfil/', views.buscar_perfil,
         name='buscar_perfil'),

]

produto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import ContasPagarDeleteView, ContasPagarUpdateView, FornecedorDeleteView, FornecedorUpdateView, InfluenciadoresCreateView, InfluenciadoresDeleteView, InfluenciadoresUpdateView, SobreView, TipoCreateView, buscar_conta_pagar, buscar_fornecedores, buscar_produto, \
    categoria_delete, produto_delete, EstoqueVariacaoView, \
    FornecedorCreateView, GestaoEstoqueVariacao, ContasView, \
    ContasPagarCreateView, FornecedorListView, VariacaoDeleteView, TipoUpdateView, TipoDeleteView
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('detalhe_loja_admin/<slug>',
         views.DetalheProduto2.as_view(), name="detalhe_loja_admin"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),
    path('adicionaraocarrinho_admin/', views.AdicionarAoCarrinhoAdmin.as_view(),
         name="adicionaraocarrinho_admin"),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),
    path('removerdocarrinho_admin/', views.RemoverDoCarrinhoAdmin.as_view(),
         name="removerdocarrinho_admin"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('carrinho_admin/', views.CarrinhoAdmin.as_view(), name="carrinho_admin"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('resumodacompra_admin/', views.ResumoDaCompraAdmin.as_view(),
         name="resumodacompra_admin"),
    path('busca/', views.Busca.as_view(), name="busca"),
    path('produto_add/', views.produto_add.as_view(), name="produto_add"),
    path('categoria/<slug:categoria_slug>/',
         views.ListaProdutosPorCategoria.as_view(), name='lista_por_categoria'),
    path('categoria_atacado/<slug:categoriaatacado_slug>/',
         views.ListaProdutosPorCategoriaAtacado.as_view(), name='lista_por_categoria_atacado'),
    path('tipo/<slug:tipo_slug>/',
         views.ListaProdutosPorTipo.as_view(), name='lista_por_tipo'),
    path('tipo_atacado/<slug:tipoatacado_slug>/',
         views.ListaProdutosPorTipoAtacado.as_view(), name='lista_por_tipo_atacado'),
    path('categoria_add/', views.categoria_add, name='categoria_add'),
    path('categoria/list/', views.categoria_list, name='categoria_list'),
    path('categoria_edit/<int:id>/', views.categoria_edit, name='categoria_edit'),
    path('<slug:slug>/excluir/', categoria_delete.as_view(),
         name='categoria_delete'),
    path('produto/<slug:slug>/excluir/', produto_delete.as_view(),
         name='produto_delete'),
    path('produto_edit/<int:pk>/',
         views.ProdutoUpdateView.as_view(), name='produto_edit'),
    path('<int:produto_id>/estoque_variacao/',
         EstoqueVariacaoView.as_view(), name='estoque_variacao'),
    path('variacao/<int:id>/edit/', views.variacao_edit, name='variacao_edit'),
    path('variacao_add/', views.variacao_add, name='variacao_add'),
    path('variacao_delete/<int:pk>/',
         VariacaoDeleteView.as_view(), name='variacao_delete'),
    path('contas/', ContasView.as_view(), name='contas'),
    path('novo_fornecedor/', FornecedorCreateView.as_view(),
         name='fornecedor_create'),
    path('conta_pagar/', ContasPagarCreateView.as_view(),
         name='conta_pagar'),
    path('gestao_estoque/', GestaoEstoqueVariacao,
         name='gestao_estoque'),
    path('lista_contaspagar/', views.ContasPagarListView.as_view(),
         name='lista_contaspagar'),
    path('conta_pagar_edit/<int:pk>/',
         ContasPagarUpdateView.as_view(), name='conta_pagar_edit'),
    path('conta_pagar_delete/<int:pk>/',
         ContasPagarDeleteView.as_view(), name='conta_pagar_delete'),
    path('lista_fornecedores/', FornecedorListView.as_view(),
         name='lista_fornecedores'),
    path('fornecedor_edit/<int:pk>/',
         FornecedorUpdateView.as_view(), name='fornecedor_edit'),
    path('fornecedor_delete/<int:pk>/',
         FornecedorDeleteView.as_view(), name='fornecedor_delete'),
    path('buscar_produto/', buscar_produto, name='buscar_produto'),
    path('tipo/', TipoCreateView.as_view(),
         name='tipo_create'),
    path('tipo_edit/<int:pk>/',
         TipoUpdateView.as_view(), name='tipo_edit'),
    path('tipo_delete/<int:pk>/',
         TipoDeleteView.as_view(), name='tipo_delete'),
    path('buscar_conta_pagar/', buscar_conta_pagar,
         name='buscar_conta_pagar'),
    path('buscar_fornecedores/', buscar_fornecedores,
         name='buscar_fornecedores'),
    path('influenciadores/', InfluenciadoresCreateView.as_view(),
         name='influenciadores_create'),
    path('influenciadores_edit/<int:pk>/',
         InfluenciadoresUpdateView.as_view(), name='influenciadores_edit'),
    path('influenciadores_delete/<int:pk>/',
         InfluenciadoresDeleteView.as_view(), name='influenciadores_delete'),
    path('lista_influenciadores/', views.InfluenciadoresListView.as_view(),
         name='lista_influenciadores'),
    path('sobre/', SobreView.as_view(), name='sobre'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pedido/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from vendas.models import Vendedor


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('C', 'Criado'),
            ('A', 'Aprovado'),
        )
    )
    data = models.DateField(default=timezone.now,
                            verbose_name='Data do pedido')
    pagamento = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('C', 'Cartão'),
            ('D', 'Dinheiro'),
        )
    )
    vendedor = models.ForeignKey(
        Vendedor, on_delete=models.CASCADE, blank=True, null=True)

    @staticmethod
    def obter_quantidade_aprovados_por_dia(data):
        return Pedido.objects.filter(status='A', data=data).count()

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_modalidade = models.CharField(
        max_length=255, blank=True, null=True)
    produto_cor = models.CharField(max_length=255, blank=True, null=True)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'


class Devolucao(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    pagamento = models.CharField(
        max_length=255, verbose_name="Tipo de pagamento")
    observacoes = models.CharField(
        max_length=255, verbose_name="Observações")

    data = models.DateField(default=timezone.now,
                            verbose_name='Data da devolução')

    def __str__(self):
        return f'Devolução do pedido {self.pedido}'

    class Meta:
        verbose_name = 'Devolução do pedido'
        verbose_name_plural = 'Devoluções do pedido'


class Cupom(models.Model):
    codigo = models.CharField(max_length=50)
    valor = models.FloatField()

    def __str__(self):
        return self.codigo

pedido/forms.py
from .models import Cupom, Devolucao, Pedido
from django import forms


class DevolucaoForm(forms.ModelForm):
    class Meta:
        model = Devolucao
        fields = '__all__'


class CupomForm(forms.ModelForm):
    class Meta:
        model = Cupom
        fields = ['codigo', 'valor']


class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['status', 'data', 'pagamento', 'vendedor', 'usuario']


class PagamentoForm(forms.Form):
    nome_cliente = forms.CharField(label='Nome do Cliente')
    cpf_cnpj = forms.CharField(label='CPF/CNPJ')
    numero_cartao = forms.CharField(
        label='Número do Cartão de Crédito')
    mes_validade = forms.CharField(label='Mês de Validade')
    ano_validade = forms.CharField(label='Ano de Validade')
    ccv = forms.CharField(label='CCV')
    email = forms.EmailField(
        label='Email')
    endereco = forms.CharField(label='Endereço')
    cep = forms.CharField(label='CEP')
    telefone = forms.CharField(label='Telefone')

templates/parciais/_carrinho.html
{% load static %}
{% load omfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
            </td>
            <td>
                <a href="{% url 'produto:detalhe' linha.slug %}">
                    {{ linha.produto_nome }}
                </a>

                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                    <i class="fa fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
                <a class="ml-3" href="{% url 'produto:adicionaraocarrinho' %}?vid={{linha.variacao_id}}">
                    <!--o ?vid={{linha.variacao_id}}, é para inserir o id do produto na url que será removida-->
                    <i class="fa fa-plus-circle text-center" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{ linha.variacao_nome }}</td>
            <td>
                {{ linha.quantidade }} x
                {% if linha.preco_unitario_promocional %}
                {{ linha.preco_unitario_promocional }}
                {% else %}
                {{ linha.preco_unitario }}
                {% endif %}
            </td>

            {% if linha.preco_quantitativo_promocional %}
            <td>{{ linha.preco_quantitativo_promocional|formata_preco }}</td>
            {% else %}
            <td>{{ linha.preco_quantitativo|formata_preco }}</td>
            {% endif %}

        </tr>
        {% endfor %}


    </table>
</div>

templates/parciais/_messages.html
{% block conteudo %}
{% if messages %}
<br>
{% for message in messages %}
<div class="{{ message.tags }}" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endblock %}

templates/parciais/_pedido.html
{% load static %}

{% load omfilters %}


{% block conteudo %}



<!-- Main Section-->
<section class="mt-0 ">
    <!-- Page Content Goes Here -->

    <!-- Breadcrumbs-->
    <div class="bg-dark py-6">
        <div class="container-fluid">
            <nav class="m-0" aria-label="breadcrumb">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item breadcrumb-light"><a>Início</a></li>
                    <li class="breadcrumb-item breadcrumb-light"><a>Lista de pedidos</a></li>
                    <li class="breadcrumb-item  breadcrumb-light active" aria-current="page">Itens do Pedido</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- / Breadcrumbs-->

    <div class="container-fluid mt-5">

        <!-- Product Top Section-->
        <div class="row">
            <div class="col">
                <br>
                <h3>{{ pedido }}</h3>

                <div class="row mt-4">
                    <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
                    <div class="col-lg-4">{{ pedido.id }}</div>
                    <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
                    <div class="col-lg-4">{{ pedido.total}}</div>

                    <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
                    <div class="col-lg-4">{{ pedido.qtd_total }}</div>
                    <div class="col-lg-2 font-weight-bold">Status:</div>
                    <div class="col-lg-4">{{ pedido.get_status_display }}</div>
                </div>

                <div class="row mt-4">
                    <div class="col">
                        <h3>Produtos</h3>
                    </div>
                </div>

                <div class="table-responsive mt-3">
                    <table class="table">
                        <tr>
                            <th class="d-none d-lg-block">Imagem</th>
                            <th>Produto</th>
                            <th>V.</th>
                            <th>QTD.</th>
                            <th>Total</th>
                        </tr>

                        {% for linha in pedido.itempedido_set.all %}
                        <tr>
                            <td class="d-none d-lg-block">
                                <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}"
                                    style="width: 150px;">
                            </td>
                            <td>{{ linha.produto }}</td>
                            <td>{{ linha.variacao }}</td>
                            <td>{{ linha.quantidade }}</td>
                            <td>
                                {% if linha.preco_promocional %}
                                {{ linha.preco_promocional|formata_preco }}
                                {% else %}
                                {{ linha.preco|formata_preco }}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>
        </div>
        <!-- / Product Information-->
    </div>
    <!-- / Product Top Section-->


    </div>

    <!-- /Page Content -->
</section>
<!-- / Main Section-->

{% endblock %}

templates/parciais/_pedido_admin.html
{% load static %}

{% load omfilters %}


{% block conteudo %}



<!-- Main Section-->
<section class="mt-0 ">
 <!-- Page Content Goes Here -->

 <div class="container-fluid mt-5">

  <!-- Product Top Section-->
  <div class="row">
   <div class="col">
    <br>
    <h3>{{ pedido }}</h3>

    <div class="row mt-4">
     <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
     <div class="col-lg-4">{{ pedido.id }}</div>
     <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
     <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>

     <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
     <div class="col-lg-4">{{ pedido.qtd_total }}</div>
     <div class="col-lg-2 font-weight-bold">Status:</div>
     <div class="col-lg-4">{{ pedido.get_status_display }}</div>
    </div>

    <div class="row mt-4">
     <div class="col">
      <h3>Produtos</h3>
     </div>
    </div>

    <div class="table-responsive mt-3">
     <table class="table">
      <tr>
       <th class="d-none d-lg-block">Imagem</th>
       <th>Produto</th>
       <th>V.</th>
       <th>QTD.</th>
       <th>Total</th>
      </tr>

      {% for linha in pedido.itempedido_set.all %}
      <tr>
       <td class="d-none d-lg-block">
        <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}" style="width: 150px;">
       </td>
       <td>{{ linha.produto }}</td>
       <td>{{ linha.variacao }}</td>
       <td>{{ linha.quantidade }}</td>
       <td>
        {% if linha.preco_promocional %}
        {{ linha.preco_promocional|formata_preco }}
        {% else %}
        {{ linha.preco|formata_preco }}
        {% endif %}
       </td>
      </tr>
      {% endfor %}

     </table>
    </div>
   </div>
  </div>
  <!-- / Product Information-->
 </div>
 <!-- / Product Top Section-->


 </div>

 <!-- /Page Content -->
</section>
<!-- / Main Section-->

{% endblock %}

templates/parciais/nav_dashboard.html
<!-- parciais/nav.html -->
{% load static %}
<nav class="bg-white border-b border-gray-200 fixed z-30 w-full">
  <div class="px-3 py-3 lg:px-5 lg:pl-3">
    <div class="flex items-center justify-between">
      <div class="flex items-center justify-start">
        <button id="toggleSidebarMobile" aria-expanded="true" aria-controls="sidebar"
          class="lg:hidden mr-2 text-gray-600 hover:text-gray-900 cursor-pointer p-2 hover:bg-gray-100 focus:bg-gray-100 focus:ring-2 focus:ring-gray-100 rounded">
          <svg id="toggleSidebarMobileHamburger" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
              clip-rule="evenodd"></path>
          </svg>
          <svg id="toggleSidebarMobileClose" class="w-6 h-6 hidden" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
              clip-rule="evenodd"></path>
          </svg>
        </button>
        <a href="{% url 'gestao:dashboard' %}" class="text-xl font-bold flex items-center lg:ml-2.5">
          <img src="{% static 'images/logos/logoab22.png'%}" class="h-10 mr-2" alt="Windster Logo">

        </a>
        <form action="#" method="GET" class="hidden lg:block lg:pl-32">
          <label for="topbar-search" class="sr-only">Search</label>
          <div class="mt-1 relative lg:w-64">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                  clip-rule="evenodd"></path>
              </svg>
            </div>
            <input type="text" name="email" id="topbar-search"
              class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-cyan-600 focus:border-cyan-600 block w-full pl-10 p-2.5"
              placeholder="Search">
          </div>
        </form>
      </div>
      <div class="flex items-center">

        <button id="toggleSidebarMobileSearch" type="button"
          class="lg:hidden text-gray-500 hover:text-gray-900 hover:bg-gray-100 p-2 rounded-lg">
          <span class="sr-only">Search</span>

          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
              clip-rule="evenodd"></path>
          </svg>
        </button>
        <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          type="button">MINHA CONTA <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor"
            viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
          </svg></button>
        <!-- Dropdown menu -->
        <div id="dropdown"
          class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
          <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">

            <li>
              <a href="{% url 'produto:lista' %}"
                class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Catálogo</a>
            </li>
            <li>
              <a href="{% url 'perfil:logout' %}"
                class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Sair</a>
            </li>

        </div>


      </div>
    </div>
  </div>
</nav>