loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('cliente/', include('cliente.urls')),
    path('vendas/', include('vendas.urls')),
    path('gestao/', include('gestao.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path

from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:id>', views.pagar, name='pagar'),
    path('pedido_sucesso/', views.SucessoView.as_view(), name='pedido_sucesso'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('salvarpedido_admin/', views.SalvarPedidoAdmin.as_view(),
         name='salvarpedido_admin'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
    path('lista_admin/', views.lista_admin.as_view(), name='lista_admin'),
    path('detalhe_admin/<int:pk>',
         views.detalhe_admin, name='detalhe_admin'),
    path('pedido/<int:pk>/excluir/', views.excluir_pedido, name='excluir_pedido'),
    path('nova_devolucao/', views.DevolucaoCreateView.as_view(),
         name='devolucao_create'),
    path('criar_novo_pedido/', views.criar_novo_pedido.as_view(),
         name='criar_novo_pedido'),
    path('lista_devolucao/', views.DevolucaoListView.as_view(),
         name='lista_devolucao'),
    path('devolucao_edit/<int:pk>/',
         views.DevolucaoUpdateView.as_view(), name='devolucao_edit'),
    path('devolucao_delete/<int:pk>/',
         views.DevolucaoDeleteView.as_view(), name='devolucao_delete'),
    path('pedido_edit/<int:pk>/',
         views.PedidoUpdateView.as_view(), name='pedido_edit'),
    path('buscar_pedido', views.buscar_pedido,
         name='buscar_pedido'),
    path('buscar_devolucao', views.buscar_devolucao,
         name='buscar_devolucao'),
    path('novo_cupom/', views.CupomCreateView.as_view(),
         name='cupom_create'),
    path('lista_cupom/', views.CupomListView.as_view(),
         name='lista_cupom'),
    path('cupom_edit/<int:pk>/',
         views.CupomUpdateView.as_view(), name='cupom_edit'),
    path('cupom_delete/<int:pk>/',
         views.CupomDeleteView.as_view(), name='cupom_delete'),






]

perfil/urls.py
from django.urls import path

from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('lista_perfis/', views.PerfilListView.as_view(),
         name='lista_perfis'),
    path('buscar_perfil/', views.buscar_perfil,
         name='buscar_perfil'),

]

produto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import ContasPagarDeleteView, ContasPagarUpdateView, FornecedorDeleteView, FornecedorUpdateView, InfluenciadoresCreateView, InfluenciadoresDeleteView, InfluenciadoresUpdateView, SobreView, TipoCreateView, buscar_conta_pagar, buscar_fornecedores, buscar_produto, \
    categoria_delete, produto_delete, EstoqueVariacaoView, \
    FornecedorCreateView, GestaoEstoqueVariacao, ContasView, \
    ContasPagarCreateView, FornecedorListView, VariacaoDeleteView, TipoUpdateView, TipoDeleteView
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('detalhe_loja_admin/<slug>',
         views.DetalheProduto2.as_view(), name="detalhe_loja_admin"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),
    path('adicionaraocarrinho_admin/', views.AdicionarAoCarrinhoAdmin.as_view(),
         name="adicionaraocarrinho_admin"),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),
    path('removerdocarrinho_admin/', views.RemoverDoCarrinhoAdmin.as_view(),
         name="removerdocarrinho_admin"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('carrinho_admin/', views.CarrinhoAdmin.as_view(), name="carrinho_admin"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('resumodacompra_admin/', views.ResumoDaCompraAdmin.as_view(),
         name="resumodacompra_admin"),
    path('busca/', views.Busca.as_view(), name="busca"),
    path('produto_add/', views.produto_add.as_view(), name="produto_add"),
    path('categoria/<slug:categoria_slug>/',
         views.ListaProdutosPorCategoria.as_view(), name='lista_por_categoria'),
    path('categoria_atacado/<slug:categoriaatacado_slug>/',
         views.ListaProdutosPorCategoriaAtacado.as_view(), name='lista_por_categoria_atacado'),
    path('tipo/<slug:tipo_slug>/',
         views.ListaProdutosPorTipo.as_view(), name='lista_por_tipo'),
    path('tipo_atacado/<slug:tipoatacado_slug>/',
         views.ListaProdutosPorTipoAtacado.as_view(), name='lista_por_tipo_atacado'),
    path('categoria_add/', views.categoria_add, name='categoria_add'),
    path('categoria/list/', views.categoria_list, name='categoria_list'),
    path('categoria_edit/<int:id>/', views.categoria_edit, name='categoria_edit'),
    path('<slug:slug>/excluir/', categoria_delete.as_view(),
         name='categoria_delete'),
    path('produto/<slug:slug>/excluir/', produto_delete.as_view(),
         name='produto_delete'),
    path('produto_edit/<int:pk>/',
         views.ProdutoUpdateView.as_view(), name='produto_edit'),
    path('<int:produto_id>/estoque_variacao/',
         EstoqueVariacaoView.as_view(), name='estoque_variacao'),
    path('variacao/<int:id>/edit/', views.variacao_edit, name='variacao_edit'),
    path('variacao_add/', views.variacao_add, name='variacao_add'),
    path('variacao_delete/<int:pk>/',
         VariacaoDeleteView.as_view(), name='variacao_delete'),
    path('contas/', ContasView.as_view(), name='contas'),
    path('novo_fornecedor/', FornecedorCreateView.as_view(),
         name='fornecedor_create'),
    path('conta_pagar/', ContasPagarCreateView.as_view(),
         name='conta_pagar'),
    path('gestao_estoque/', GestaoEstoqueVariacao,
         name='gestao_estoque'),
    path('lista_contaspagar/', views.ContasPagarListView.as_view(),
         name='lista_contaspagar'),
    path('conta_pagar_edit/<int:pk>/',
         ContasPagarUpdateView.as_view(), name='conta_pagar_edit'),
    path('conta_pagar_delete/<int:pk>/',
         ContasPagarDeleteView.as_view(), name='conta_pagar_delete'),
    path('lista_fornecedores/', FornecedorListView.as_view(),
         name='lista_fornecedores'),
    path('fornecedor_edit/<int:pk>/',
         FornecedorUpdateView.as_view(), name='fornecedor_edit'),
    path('fornecedor_delete/<int:pk>/',
         FornecedorDeleteView.as_view(), name='fornecedor_delete'),
    path('buscar_produto/', buscar_produto, name='buscar_produto'),
    path('tipo/', TipoCreateView.as_view(),
         name='tipo_create'),
    path('tipo_edit/<int:pk>/',
         TipoUpdateView.as_view(), name='tipo_edit'),
    path('tipo_delete/<int:pk>/',
         TipoDeleteView.as_view(), name='tipo_delete'),
    path('buscar_conta_pagar/', buscar_conta_pagar,
         name='buscar_conta_pagar'),
    path('buscar_fornecedores/', buscar_fornecedores,
         name='buscar_fornecedores'),
    path('influenciadores/', InfluenciadoresCreateView.as_view(),
         name='influenciadores_create'),
    path('influenciadores_edit/<int:pk>/',
         InfluenciadoresUpdateView.as_view(), name='influenciadores_edit'),
    path('influenciadores_delete/<int:pk>/',
         InfluenciadoresDeleteView.as_view(), name='influenciadores_delete'),
    path('lista_influenciadores/', views.InfluenciadoresListView.as_view(),
         name='lista_influenciadores'),
    path('sobre/', SobreView.as_view(), name='sobre'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pedido/models.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from vendas.models import Vendedor


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('C', 'Criado'),
            ('A', 'Aprovado'),
        )
    )
    data = models.DateField(default=timezone.now,
                            verbose_name='Data do pedido')
    pagamento = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('C', 'Cartão'),
            ('D', 'Dinheiro'),
        )
    )
    vendedor = models.ForeignKey(
        Vendedor, on_delete=models.CASCADE, blank=True, null=True)

    @staticmethod
    def obter_quantidade_aprovados_por_dia(data):
        return Pedido.objects.filter(status='A', data=data).count()

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_modalidade = models.CharField(
        max_length=255, blank=True, null=True)
    produto_cor = models.CharField(max_length=255, blank=True, null=True)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'


class Devolucao(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    pagamento = models.CharField(
        max_length=255, verbose_name="Tipo de pagamento")
    observacoes = models.CharField(
        max_length=255, verbose_name="Observações")

    data = models.DateField(default=timezone.now,
                            verbose_name='Data da devolução')

    def __str__(self):
        return f'Devolução do pedido {self.pedido}'

    class Meta:
        verbose_name = 'Devolução do pedido'
        verbose_name_plural = 'Devoluções do pedido'


class Cupom(models.Model):
    codigo = models.CharField(max_length=50)
    valor = models.FloatField()

    def __str__(self):
        return self.codigo

pedido/forms.py
from .models import Cupom, Devolucao, Pedido
from django import forms


class DevolucaoForm(forms.ModelForm):
    class Meta:
        model = Devolucao
        fields = '__all__'


class CupomForm(forms.ModelForm):
    class Meta:
        model = Cupom
        fields = ['codigo', 'valor']


class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['status', 'data', 'pagamento', 'vendedor', 'usuario']


class PagamentoForm(forms.Form):
    nome_cliente = forms.CharField(label='Nome do Cliente')
    cpf_cnpj = forms.CharField(label='CPF/CNPJ')
    numero_cartao = forms.CharField(
        label='Número do Cartão de Crédito')
    mes_validade = forms.CharField(label='Mês de Validade')
    ano_validade = forms.CharField(label='Ano de Validade')
    ccv = forms.CharField(label='CCV')
    email = forms.EmailField(
        label='Email')
    endereco = forms.CharField(label='Endereço')
    cep = forms.CharField(label='CEP')
    telefone = forms.CharField(label='Telefone')

pedido/templates/pedido/carrinho_admin.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}
{% load static %}
{% block titulo %}Pedidos{% endblock %}

{% block content %}
<br><br><br><br><br>
{% if carrinho %}
<!-- Main Section-->
<section class="mt-0 overflow-lg-hidden  ">
  <!-- Page Content Goes Here -->
  <div class="container">
    <div class="row g-0 ">
      <div class="col-12 col-lg-7 pt-5 pt-lg-10">
        <div class="pe-lg-5">


          <div class="mt-5">
            <h3 class="fs-5 fw-bolder mb-0 border-bottom pb-4">Seu Carrinho</h3>
            {% for linha in carrinho.values %}
            <div class="table-responsive">
              <table class="table align-middle">
                <tbody class="border-0">
                  <!-- Cart Item-->
                  <div class="row mx-0 py-4 g-0 border-bottom">
                    <div class="col-2 position-relative">
                      <picture class="d-block border">
                        <img class="img-fluid" src="{% get_media_prefix %}{{ linha.imagem }}"
                          alt="HTML Bootstrap Template by Pixel Rocket">
                      </picture>
                    </div>
                    <div class="col-9 offset-1">
                      <div>
                        <h6 class="justify-content-between d-flex align-items-start mb-2">
                          {{ linha.produto_nome }}
                          <a style="text-decoration:none;"
                            href="{% url 'produto:removerdocarrinho_admin' %}?vid={{ linha.variacao_id }}"><i
                              class="fa-solid fa-minus"></i></a>
                        </h6>
                        <span class="d-block text-muted fw-bolder text-uppercase fs-9">
                          Tamanho: {{ linha.variacao_nome }}<br>
                          Quantidade: {{ linha.quantidade }}<a style="text-decoration:none;"
                            href="{% url 'produto:adicionaraocarrinho' %}?vid={{linha.variacao_id}}">
                            <i class="fa-solid fa-plus"></i>
                          </a>
                        </span>
                      </div>
                      <p class="fw-bolder text-end text-muted m-0">
                        {% if linha.preco_quantitativo_promocional %}
                        {{ linha.preco_quantitativo_promocional|formata_preco }}
                        {% else %}
                        {{ linha.preco_quantitativo|formata_preco }}
                        {% endif %}
                      </p>
                    </div>
                  </div> <!-- / Cart Item-->
                </tbody>
              </table>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-5 bg-light pt-lg-10 aside-checkout pb-5 pb-lg-0 my-5 my-lg-0">
        <div class="p-4 py-lg-0 pe-lg-0 ps-lg-5">
          <div class="pb-4 border-bottom">
            <div class="d-flex flex-column flex-md-row justify-content-md-between mb-4 mb-md-2">
              <div>
                <p class="m-0 fw-bold fs-5">Total</p>
              </div>
              <p class="m-0 fs-5 fw-bold">{{ carrinho|cart_totals|formata_preco }}</p>
            </div>
          </div>
          <div class="py-4">
            <div class="input-group mb-0">
              <input type="text" class="form-control" placeholder="Insira seu cupom">
              <button class="btn btn-secondary btn-sm px-4">Aplicar</button>
            </div>
          </div>
          <div class="col-lg mt-auto">

            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-dark" href="{% url 'produto:resumodacompra_admin' %}">
              Comprar
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
              Entrar ou cadastrar e comprar
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- /Page Content -->
</section>
<!-- / Main Section-->




{% else %}
<section class="mt-0 overflow-lg-hidden  vh-lg-100">
  <!-- Page Content Goes Here -->
  <div class="container">
    <div class="row g-0 vh-lg-100">
      <div class="col-12 col-lg-7 pt-5 pt-lg-10">
        <div class="pe-lg-5">

          <nav class="d-none d-md-block">
            <ul class="list-unstyled d-flex justify-content-start mt-4 align-items-center fw-bolder small">
              <li class="me-4"><a class="nav-link-checkout active" href="./cart.html">Seu Carrinho</a>
              </li>
              <li class="me-4"><a class="nav-link-checkout " href="./checkout.html">Detalhes</a>
              </li>
              <li class="me-4"><a class="nav-link-checkout " href="./checkout-shipping.html">Envio</a>
              </li>
              <li><a class="nav-link-checkout nav-link-last " href="./checkout-payment.html">Pagamento</a>
              </li>
            </ul>
          </nav>
          <div class="mt-5">
            <h3 class="fs-5 fw-bolder mb-0 border-bottom pb-4">Não há produtos no seu carrinho!</h3>

          </div>
        </div>
      </div>

    </div>
  </div>

  <!-- /Page Content -->
</section>


{% endif %}




{% endblock %}

pedido/templates/pedido/lista_admin.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}

<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

    <div class="flex items-center justify-between mb-4">
        <div class="flex-shrink-0"><br><br><br>
            <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Todos os pedidos</span><br><br>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4 col-sm-4">
            <div class="d-flex justify-content-center">
                <form class="input-group" action="{% url 'pedido:buscar_pedido' %}" method="GET">
                    <input type="text" class="form-control" placeholder="Pesquise pelo Nº do pedido" name="q"
                        aria-label="Pesquisar">
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div><br>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Pedido
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Usuário
                    </th>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Total
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Qtd. Itens
                    </th>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Status
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Mais detalhes
                    </th>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Data
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Tipo de pagamento
                    </th>
                    <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
                        Ações
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidosadmin %}
                <tr class="border-b border-gray-200 dark:border-gray-700">
                    <th scope="row"
                        class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
                        {{ pedido }}
                    </th>
                    <td class="px-6 py-4">
                        {{ pedido.usuario }}
                    </td>
                    <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                        {{ pedido.total|formata_preco }}
                    </td>
                    <td class="px-6 py-4">
                        {{ pedido.qtd_total }}
                    </td>
                    <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                        {{ pedido.get_status_display }}
                    </td>
                    <td class="px-6 py-4">
                        <a href="{% url 'pedido:detalhe_admin' pedido.id %}">
                            Ver <i class="fa fa-search-plus ml-2"></i>
                        </a>
                    </td>
                    <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                        {{ pedido.data }}
                    </td>
                    <td class="px-6 py-4">
                        {{ pedido.get_pagamento_display }}
                    </td>

                    <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
                        <a href="{% url 'pedido:pedido_edit' pedido.id %}">
                            <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
                        </a>
                        <a href="{% url 'pedido:excluir_pedido' pedido.id %}">
                            <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>




{% include 'parciais/_pagination.html' %}

{% endblock %}

pedido/templates/pedido/lista_cupom.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}



<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

  <div class="flex items-center justify-between mb-4">
    <div class="flex-shrink-0"><br><br><br>
      <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Cupons da
        loja!</span><br><br>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-sm-4">
      <div class="d-flex justify-content-center">
        <form class="input-group" action="{% url 'pedido:buscar_devolucao' %}" method="GET">
          <input type="text" class="form-control" placeholder="Pesquisar pelo Nº do pedido" name="q"
            aria-label="Pesquisar">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div><br>

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Nome
          </th>
          <th scope="col" class="px-6 py-3">
            Valor
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Ações
          </th>

        </tr>
      </thead>
      <tbody>
        {% for cupom in cupons %}
        <tr class="border-b border-gray-200 dark:border-gray-700">
          <th scope="row"
            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
            {{ cupom.codigo }}
          </th>
          <td class="px-6 py-4">
            {{ cupom.valor }}%
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            <a href="{% url 'pedido:cupom_edit' cupom.id %}">
              <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
            </a>
            <a href="{% url 'pedido:cupom_delete' cupom.id %}">
              <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
            </a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</div>



{% include 'parciais/_pagination.html' %}



{% endblock %}

pedido/templates/pedido/lista_devolucao.html
{% extends "parciais/base_dashboard.html" %}
{% load omfilters %}

{% block titulo %}Pedidos{% endblock %}

{% block content %}



<div class="bg-white shadow rounded-lg p-4 sm:p-6 xl:p-8  2xl:col-span-2">

  <div class="flex items-center justify-between mb-4">
    <div class="flex-shrink-0"><br><br><br>
      <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">Devoluções dos pedidos da
        loja!</span><br><br>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-sm-4">
      <div class="d-flex justify-content-center">
        <form class="input-group" action="{% url 'pedido:buscar_devolucao' %}" method="GET">
          <input type="text" class="form-control" placeholder="Pesquisar pelo Nº do pedido" name="q"
            aria-label="Pesquisar">
          <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div><br>

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Usuário
          </th>
          <th scope="col" class="px-6 py-3">
            Pedido
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Total
          </th>
          <th scope="col" class="px-6 py-3">
            Tipo de pagamento
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Observações
          </th>
          <th scope="col" class="px-6 py-3">
            Data
          </th>
          <th scope="col" class="px-6 py-3 bg-gray-50 dark:bg-gray-800">
            Ações
          </th>

        </tr>
      </thead>
      <tbody>
        {% for devolucao in devolucoes %}
        <tr class="border-b border-gray-200 dark:border-gray-700">
          <th scope="row"
            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-50 dark:text-white dark:bg-gray-800">
            {{ devolucao.usuario }}
          </th>
          <td class="px-6 py-4">
            {{ devolucao.pedido }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            R$ {{ devolucao.pedido.total|floatformat:2 }}
          </td>
          <td class="px-6 py-4">
            {{ devolucao.pagamento }}
          </td>
          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            {{ devolucao.observacoes }}
          </td>
          <td class="px-6 py-4">
            {{ devolucao.data }}
          </td>

          <td class="px-6 py-4 bg-gray-50 dark:bg-gray-800">
            <a href="{% url 'pedido:devolucao_edit' devolucao.id %}">
              <i class="fa-solid fa-pen-to-square fa-xl" style="color:mediumblue"></i>
            </a>
            <a href="{% url 'pedido:devolucao_delete' devolucao.id %}">
              <i class="fa-solid fa-trash fa-xl" style="color: red;"></i>
            </a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</div>



{% include 'parciais/_pagination.html' %}



{% endblock %}